
name: CI - Sistema de Pagamentos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install

      # 4. Executar testes
      - name: Rodar testes
        run: npm test

      # 5. Gerar cobertura (opcional)
      - name: Gerar cobertura
        run: npm test -- --coverage
